### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by wahowaho** [max-verstrappon/common-starters#2]
问您个问题，就是minio 是如何改变单个文件的权限的，  ossClient.getS3Client().setObjectAcl(ossProperties.getBucketName(), key, CannedAccessControlList.Private); 这样改变权限接口会报错。
错误信息 
A header you provided implies functionality that is not implemented (Service: Amazon S3; Status Code: 501; Error Code: NotImplemented; Request ID: 1718A7B48A0094A0; S3 Extended Request ID: 3df21bb4-f73d-43a4-8e88-a3fa012464a4)

bucket策略用的是csdn上您写的那个，我看minio sdk 也没有改变单个文件访问权限的 api 接口啊 ，您知道吗  谢谢

**Comment by max-verstrappon** [comment]
错误是说这个你发的minio请求里有请求头是minio接口的方法没实现的问题吧;
我在csdn中发布的那个权限是针对于bucket的策略,并不能应用到对象上;

之前没遇到过到文件对象级别的权限需求, 没注意看文档;
按照AmazonS3的官方文档中尝试获取/设置minio对象的权限,获取到 NULL:FULL_CONTROL, 在尝试单独设置读或写权限之后执行是ok的, 但是查询对象权限还是FULL_CONTROL,没有得到改变
在minio文档中.不论是命令行的minio cl, SDK, minio console页面都没有提供修改对象权限的入口, 估计就是没有实现吧

以下代码, 可以自己试试看

/**
     * 无论设置哪种权限，都是返回 NULL: FULL_CONTROL*
     */
    @Test
    public void test_get_oss_object_acl() {
        final AmazonS3 s3 = ossClient.getS3Client();
        try {
            AccessControlList acl = s3.getObjectAcl("jsoup-bucket-test", "00714cfbb27f4a65bd170ed746165da8.pdf");
            List<Grant> grants = acl.getGrantsAsList();
            for (Grant grant : grants) {
                System.out.format("  %s: %s\n", grant.getGrantee().getIdentifier(), grant.getPermission().toString());
                //打印 null: FULL_CONTROL
            }
        } catch (AmazonServiceException e) {
            System.err.println(e.getErrorMessage());
            System.exit(1);
        }
    }

    /**
     * 执行通过 ok*
     */
    @Test
    public void test_set_oss_object_acl() {
        final AmazonS3 s3 = ossClient.getS3Client();
        try {
            AccessControlList acl = s3.getObjectAcl("jsoup-bucket-test", "00714cfbb27f4a65bd170ed746165da8.pdf");
//            final EmailAddressGrantee grantee = new ***@***.******@***.***>");
//            final CanonicalGrantee grantee = new CanonicalGrantee("这里使用唯一标记id:例如用户ID");
            /*
                public enum Permission {
                    FullControl("FULL_CONTROL", "x-amz-grant-full-control"),
                    Read("READ", "x-amz-grant-read"),
                    Write("WRITE", "x-amz-grant-write"),
                    ReadAcp("READ_ACP", "x-amz-grant-read-acp"),
                    WriteAcp("WRITE_ACP", "x-amz-grant-write-acp");
                 }
             */
            acl.grantPermission(GroupGrantee.AuthenticatedUsers, Permission.Read);
            s3.setObjectAcl("jsoup-bucket-test", "00714cfbb27f4a65bd170ed746165da8.pdf", acl);
        } catch (AmazonServiceException e) {
            System.err.println(e.getErrorMessage());
            System.exit(1);
        }
    }



On Sep 27, 2022, at 15:57, whhhhhhhh ***@***.******@***.***>> wrote:



问您个问题，就是minio 是如何改变单个文件的权限的， ossClient.getS3Client().setObjectAcl(ossProperties.getBucketName(), key, CannedAccessControlList.Private); 这样改变权限接口会报错。
错误信息
A header you provided implies functionality that is not implemented (Service: Amazon S3; Status Code: 501; Error Code: NotImplemented; Request ID: 1718A7B48A0094A0; S3 Extended Request ID: 3df21bb4-f73d-43a4-8e88-a3fa012464a4)

bucket策略用的是csdn上您写的那个，我看minio sdk 也没有改变单个文件访问权限的 api 接口啊 ，您知道吗 谢谢

**Comment by wahowaho** [comment]
![image](https://user-images.githubusercontent.com/28621460/192927708-6c544453-2b49-4edb-a18f-70a7a1882579.png)
打扰了，用您这个还是实现不了对应的权限修正，我用了另一种方式。修正相对路径上的访问权限（修改策略）来控制文件的显隐，一个路径下就一个文件，不知道我这样的处理方式是否有问题。代码如下：
` BucketPolicy bucketPolicy = ossClient.getS3Client().getBucketPolicy(ossProperties.getBucketName());
        // {"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"AWS":["*"]},"Action":["s3:GetBucketLocation"],"Resource":["arn:aws:s3:::bucket"]},{"Effect":"Allow","Principal":{"AWS":["*"]},"Action":["s3:ListBucket"],"Resource":["arn:aws:s3:::bucket"],"Condition":{"StringEquals":{"s3:prefix":["22/1","22/2"]}}},{"Effect":"Allow","Principal":{"AWS":["*"]},"Action":["s3:GetObject"],"Resource":["arn:aws:s3:::bucket/22/1*","arn:aws:s3:::bucket/22/2*"]}]}
        JSONObject jsonObject = JSON.parseObject(bucketPolicy.getPolicyText());
        if (jsonObject == null){
            log.error("上线发生错误【{}】",key);
            return;
        }
        JSONArray statement = jsonObject.getJSONArray("Statement");
        statement.forEach( e -> {
            if (e.toString().contains("s3:prefix")) {
                JSONObject sub = JSON.parseObject(e);
                JSONObject condition = sub.getJSONObject("Condition");
                JSONObject stringEquals = condition.getJSONObject("StringEquals");
                JSONArray jsonArray = stringEquals.getJSONArray("s3:prefix");
                String substring = key.substring(0, key.lastIndexOf("/"));
                if (jsonArray.contains(substring)){
                    return;
                }
                jsonArray.add(substring);
            }

            if (e.toString().contains("s3:GetObject")) {
                JSONObject sub = JSON.parseObject(e);
                JSONArray resource = sub.getJSONArray("Resource");
                String substring = key.substring(0, key.lastIndexOf("/"));
                // "arn:aws:s3:::bucket/22/1*",
                String word = "arn:aws:s3:::" + ossProperties.getBucketName() +"/"+substring + "*";
                if (resource.contains(word)){
                    return;
                }
                resource.add(word);
            }
        });
        // ossClient.getS3Client().setObjectAcl(ossProperties.getBucketName(), key, CannedAccessControlList.PublicRead);
        ossClient.bucketPolicy(ossProperties.getBucketName(), jsonObject.toJSONString());`

**Comment by max-verstrappon** [comment]
第一个回复的意思是 在minio没有实现对于文件对象的权限控制, 并没有说能实现权限控制
