### ISSUE TITLE
join-in-memory-common-spring-boot-starter 优化建议

### ISSUE THREAD

**Issue by CiBeDer** [max-verstrappon/common-starters#3]
业务场景：
1. VO(updateId, createId,updateName,createName)
2. 需要查询两次数据库  建议合并

**Comment by hp-coder** [comment]
描述不够具体;

目前的描述下
场景1: updateId 和 createId 值不同, 两个name字段就需要分别查
场景2: updateId 和 createId 值相同, 才可能继续讨论是否需要合并的问题

如果还需沟通可以把你的场景描述一下, 有代码片段最好. 

谢谢

**Comment by max-verstrappon** [comment]
如果一个类的多个属性使用的注解是同一个的话可以考虑合并, 我先研究下如何实现.

**Comment by max-verstrappon** [comment]
experiment 分支更新了合并分组join的新特性

因为这种使用Spring @AliasFor的嵌套注解, 可以自定义实现重写根注解的属性值, 所以在研究后选择了部分JoinInMemory中的属性作为不变标记生成分组key来实现同类注解合并的效果;

在join的example模块测试中简单测试了下, 效果还行.
